---
- name: Install Python 3 and Pip
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip

- name: Install PyMySQL
  ansible.builtin.pip:
    name: pymysql
    executable: pip3

- name: Ensure MySQL users use caching_sha2_password for authentication
  community.mysql.mysql_user:
    login_user: "{{ db_root_user }}"
    login_password: "{{ db_root_password }}"
    user: "{{ item.key }}"
    host: "localhost"
    password: "{{ item.value }}"
    plugin: caching_sha2_password
    state: present
  with_dict: "{{ db_users_passwords }}"
