---
- name: Remove metadata from wordpress
  ansible.builtin.blockinfile:
      path: "/var/www/html/wp-content/themes/twentytwenty/functions.php"
      block: |
        function itsme_disable_feed() {
            wp_die( __( 'No feed available, please visit the <a href="'. esc_url( home_url( '/' ) ) .'">homepage</a>!' ) );
          }
          add_action('do_feed', 'itsme_disable_feed', 1);
          add_action('do_feed_rdf', 'itsme_disable_feed', 1);
          add_action('do_feed_rss', 'itsme_disable_feed', 1);
          add_action('do_feed_rss2', 'itsme_disable_feed', 1);
          add_action('do_feed_atom', 'itsme_disable_feed', 1);
          add_action('do_feed_rss2_comments', 'itsme_disable_feed', 1);
          add_action('do_feed_atom_comments', 'itsme_disable_feed', 1);
          remove_action( 'wp_head', 'feed_links_extra', 3 );
          remove_action( 'wp_head', 'feed_links', 2 );

          function remove_wp_version() {
              return '';
          }
          add_filter('the_generator', 'remove_wp_version');

          function remove_wp_version_scripts_styles($src) {
              if (strpos($src, 'ver=' . get_bloginfo('version')))
                  $src = remove_query_arg('ver', $src);
              return $src;
          }
          add_filter('style_loader_src', 'remove_wp_version_scripts_styles', 9999);
          add_filter('script_loader_src', 'remove_wp_version_scripts_styles', 9999);

          function remove_footer_version() {
              add_filter('admin_footer_text', '__return_empty_string', 11);
              add_filter('update_footer', '__return_empty_string', 11);
          }
          add_action( 'admin_init', 'remove_footer_version' );

          function remove_dashboard_meta() {
              remove_meta_box('dashboard_right_now', 'dashboard', 'normal');
              remove_meta_box('dashboard_primary', 'dashboard', 'side');
          }
          add_action('admin_init', 'remove_dashboard_meta');
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
